server:
  port: 8762

spring:
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

