spring:
  application:
    name: zuul
  profiles:
    active: dev
zuul:
  routes:
    service-business:
      instance-id: service-business
      path: /service-business/*
    service-message:
      instance-id: service-message
      path: /service-message/*


