server:
  port:
    50000
spring:
  application:
    name: zuul
zuul:
  routes:
    service-business:
      instance-id: service-business
      path: /service-business/*
    service-message:
      instance-id: service-message
      path: /service-message/*

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

