spring:
  application:
    name: zuul
  profiles:
    active: @spring.profiles.active@
zuul:
  routes:
    service-manage:
      instance-id: service-manage
      path: /service-manage/*
    service-common:
      instance-id: service-common
      path: /service-common/*


