server:
  port:
    50000
spring:
  application:
    name: zuul
  profiles:
    active: prod

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    hostname: zuul
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
