server:
  port:
    50000
spring:
  application:
    name: zuul
  profiles:
    active: dev

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

logging:
  config: logback-spring-test.xml
  file: /keep-cloud/log/zuul.log
    max-size: 50M
