server:
  port: 50002
spring:
  profiles:
    active: dev

eureka:
  client:
    registryFetchIntervalSeconds: 30
    service-url:
      default-zone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS





