server:
  port: 50001
spring:
  profiles:
    active: dev
  security:
    user:
      name: manage
      password: manage
  datasource:
    url: jdbc:mysql://39.107.125.86:3306/keep-cloud?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=false
    driver-class-name: com.mysql.jdbc.Driver
    username: mysql
    password: Mysql123456!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  redis:
    database: 0
    host: 39.107.125.86
    port: 6379
    password: Redis123456!
    jedis:
      pool:
        max-active: 8
        max-wait: 5000ms
        max-idle: 8
        min-idle: 0
    timeout: 10000ms

eureka:
  instance:
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 30
    service-url:
      default-zone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS





