server:
  port: 50001
spring:
  application:
    name: service-business
eureka:
  client:
    enabled: true
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka/



